### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by andyfarthing** [carlashley/appleloops#5]
**Describe the bug**
Trying to run with any arguments fails with error: AttributeError: 'str' object has no attribute 'get'. The full message is:

`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/appleloops/__main__.py", line 164, in <module>
  File "/usr/local/bin/appleloops/__main__.py", line 112, in main
  File "/usr/local/bin/appleloops/loopslib/process_source.py", line 65, in __init__
  File "/usr/local/bin/appleloops/loopslib/process_source.py", line 197, in _get_pkgs
  File "/usr/local/bin/appleloops/loopslib/applications.py", line 155, in mandatory_pkgs
  File "/usr/local/bin/appleloops/loopslib/applications.py", line 146, in _get_packages
  File "/usr/local/bin/appleloops/loopslib/option_packs.py", line 25, in __init__
  File "/usr/local/bin/appleloops/loopslib/option_packs.py", line 49, in _process_packs
AttributeError: 'str' object has no attribute 'get'`

The previous version 2 seemed to work fine, but any version 3 I've tried (3.0.1, 3.0.2, 3.0.3) fails.

Using the prebuilt pkg which installs into /usr/local/bin

**Version**
v3.0.3

**Command Used**
appleloops -o -m -n -b ~/Desktop/loops.dmg --log-level DEBUG. Even a basic "appleloops -m -n" fails with the same error.

**Debug Log**
[appleloops.log](https://github.com/carlashley/appleloops/files/3521169/appleloops.log)

**Screenshots**
N/A

**Comment by jmartinez0837** [comment]
The problem seems to be with Logic. When I run "--deployment -a garageband" I get no errors, but when I add "logicpro" to the mix I get the same error.

Just some more info.

**Comment by walkintom** [comment]
Just to add my error in to the mix and the command I ran to get it:

`./appleloops --plists logicpro1050 -m -o -d /Volumes/Data/munki_repo/pkgs/appleaudio
Analysing...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./appleloops/__main__.py", line 164, in <module>
  File "./appleloops/__main__.py", line 115, in main
  File "./appleloops/loopslib/process_source.py", line 47, in __init__
TypeError: __init__() got an unexpected keyword argument 'plist'`

**Comment by carlashley** [comment]
Fixed with [v3.0.4](https://github.com/carlashley/appleloops/releases/tag/v3.0.4).

**Comment by andyfarthing** [comment]
Still seem to be getting the same error I'm afraid!

I've attached a log here - I added an additional "-a logicpro" argument as the workstation I'm on at the minute has Garageband installed, but same error with "appleloops -o -n "

I can also confirm @jmartinez0837 's comment that it seems to work fine when using "-a garageband", so it looks like a Logic thing.

[appleloops.log](https://github.com/carlashley/appleloops/files/3524654/appleloops.log)

Thanks for the help.

**Comment by walkintom** [comment]
Unfortunately, I can confirm I'm also still seeing the AttributeError. I do notice however that before I was receiving  "TypeError" whereas now I'm receiving "AttributeError".

`./appleloops --plists logicpro1050 -m -o -d /Volumes/Data/munki_repo/pkgs/appleaudio
Analysing...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./appleloops/__main__.py", line 164, in <module>
  File "./appleloops/__main__.py", line 115, in main
  File "./appleloops/loopslib/process_source.py", line 47, in __init__
  File "./appleloops/loopslib/remote_plist.py", line 36, in __init__
  File "./appleloops/loopslib/remote_plist.py", line 83, in _read_remote_plist
  File "./appleloops/loopslib/option_packs.py", line 25, in __init__
  File "./appleloops/loopslib/option_packs.py", line 49, in _process_packs
AttributeError: 'str' object has no attribute 'get'`

**Comment by MiqViq** [comment]
Meetoo!
appleloops 3.0.4 installed from the pkg that was downloaded from github.
macOS 10.14.6.

Command: appleloops -m -o -u
Result:
Analysing...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/appleloops/__main__.py", line 164, in <module>
  File "/usr/local/bin/appleloops/__main__.py", line 112, in main
  File "/usr/local/bin/appleloops/loopslib/process_source.py", line 65, in __init__
  File "/usr/local/bin/appleloops/loopslib/process_source.py", line 197, in _get_pkgs
  File "/usr/local/bin/appleloops/loopslib/applications.py", line 155, in mandatory_pkgs
  File "/usr/local/bin/appleloops/loopslib/applications.py", line 146, in _get_packages
  File "/usr/local/bin/appleloops/loopslib/option_packs.py", line 25, in __init__
  File "/usr/local/bin/appleloops/loopslib/option_packs.py", line 49, in _process_packs
AttributeError: 'str' object has no attribute 'get'

**Comment by carlashley** [comment]
Should be fixed in v3.0.5.

This Exception does not exist.
![droids](https://user-images.githubusercontent.com/9841187/63429232-d6207f00-c45c-11e9-9e2a-9138b70f1e3f.gif)

**Comment by andyfarthing** [comment]
All seems fine now, thanks!
